### ISSUE TITLE
Rewrite in CSS 

### ISSUE THREAD

**Issue by leabs** [twitter/the-algorithm#184]
**Is your feature request related to a problem? Please describe.**
Css could be faster

**Describe the solution you'd like**
```css
twitter{
    display: none;
}
```
